### ISSUE TITLE
Refresh feature

### ISSUE THREAD

**Issue by schuaBob** [BBCYM/aster#57]
Refresh not yet completed.
前端有個按鈕可以按refresh，要有防呆機制，等到後端跑完才能按下一次@michelle111 
之後有空再做往下拉可以refresh

**Comment by schuaBob** [comment]
@michelle111 做完album api，找我討論一下

**Comment by michelle111** [comment]
auth views get
auth models 
isSync(標註有沒有同步) 表示前端在gallery 如果他點了一張照片，
他每次get的時候他就會，比對有沒有在資料庫裏面，
如果沒有，
就會把去GOOGLE PHOTO API抓新十張左右的照片，
比對如果沒有，設定
isSync FALSE就需要更新

如果isFreshing 是true就不能按下去

登入的時候就已經把

使用者登入的時候，都會把isSync、isFreshing存在state裡面
state.isSync  state.isFreshing


views  put
按按鈕叫他(PUT)
傳一個sub
sub = userId(從state裡面拿)
少寫要判斷isSync

我要做的
一個從state判斷

假設剛開始使用isSync FALSE   isFreshing TRUE
每次都要先看state
tab每一點去PROFILE都要呼叫一次GET 看isSync isFreshing狀態是什麼，
(((前提是isFreshing是true，因為假設))) 
前端就要改state
