### ISSUE TITLE
Frontend - Album

### ISSUE THREAD

**Issue by schuaBob** [BBCYM/aster#59]
- delete photo @schuaBob 
- _add photo to album 先不用_
- (done)Create album by one click @schuaBob 
- delete photo from album @schuaBob 
- (done) delete album @Caicai104 , @schuaBob 
- edit album detail(title, tags) @schuaBob

**Comment by schuaBob** [comment]
Create album by one click done

**Comment by schuaBob** [comment]
delete single photo is quite tricky

**Comment by schuaBob** [comment]
Do
- delete single photo
- edit album detail(not include delete photo)

**Comment by Caicai104** [comment]
delete album done
